spring.application.name=Esercitazione_walter

# Configurazione H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2 (per vedere il database nel browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Encoding UTF-8
spring.sql.init.encoding=UTF-8
spring.datasource.sql-script-encoding=UTF-8

# AGGIUNGI QUESTA RIGA IMPORTANTE:
spring.jpa.defer-datasource-initialization=true

server.port=8082